spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/1602b
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix:  .jsp
server:
  port: 8888